//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    
    public partial class SPE_OBTIENE_C_CATALOGO_LISTA_Result
    {
        public int ID_CATALOGO_LISTA { get; set; }
        public string NB_CATALOGO_LISTA { get; set; }
        public string DS_CATALOGO_LISTA { get; set; }
        public int ID_CATALOGO_TIPO { get; set; }
        public string NB_CATALOGO_TIPO { get; set; }
        public Nullable<bool> FG_SISTEMA { get; set; }
        public Nullable<System.DateTime> FE_MODIFICACION { get; set; }
        public string CL_USUARIO_MODIFICA { get; set; }
    }
}
