
SET NUMERIC_ROUNDABORT OFF
GO
SET XACT_ABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
/*Puntero usado para actualizaciones de texto o imágenes. Puede que no sea necesario, pero se declara aquí por si lo fuera*/
DECLARE @pv binary(16)
BEGIN TRANSACTION
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (3, N'GBD', N'MENUGRAL', N'Versiones', 11, N'Administracion/Catalogos/Versiones.aspx', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS></ROOT>',1), 2)
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (4, N'GBC', N'MENUGRAL', N'Modulos', 11, N'Administracion/Catalogos/Modulos.aspx', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS></ROOT>',1), 1)
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (5, N'GBB', N'MENUGRAL', N'Sistemas', 11, N'Administracion/Catalogos/Sistemas.aspx', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS></ROOT>',1), 0)
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (6, N'GBA', N'MENUGRAL', N'Clientes', 11, N'Administracion/Catalogos/Clientes.aspx', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS></ROOT>',1), 4)
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (7, N'G', N'MENUGRAL', N'Configuración', NULL, N'', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS><ICONO URL="~/Assets/images/Icons/25/Settings.png"/></ROOT>',1), 7)
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (8, N'GA', N'MENUGRAL', N'Roles', 7, N'/Administracion/Roles.aspx', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS></ROOT>',1), 0)
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (9, N'GBE', N'MENUGRAL', N'Empresas', 11, N'Administracion/Catalogos/Empresas.aspx', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS></ROOT>',1), 6)
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (10, N'GBF', N'MENUGRAL', N'Licencias', 11, N'Administracion/Catalogos/Licencias.aspx', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS></ROOT>',1), 5)
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (11, N'GB', N'MENUGRAL', N'Catálogos', 7, N'', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS></ROOT>',1), 1)
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (12, N'H', N'MENUGRAL', N'Gestión de periodos', NULL, N'Gestion/GestionPeriodos.aspx', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS><ICONO URL="~/Assets/images/Icons/25/Manage.png"/></ROOT>',1), 0)
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (998, N'F', N'MENUGRAL', N'Home', NULL, N'/Default.aspx', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS><ICONO URL="~/Assets/images/Icons/25/home.png"/></ROOT>',1), 8)
INSERT INTO [ADM].[S_FUNCION] ([ID_FUNCION], [CL_FUNCION], [CL_TIPO_FUNCION], [NB_FUNCION], [ID_FUNCION_PADRE], [NB_URL], [XML_CONFIGURACION], [NO_ORDEN]) VALUES (999, N'E', N'MENUGRAL', N'Salir', NULL, N'/Logout.aspx', CONVERT(xml,N'<ROOT><MODULOS><MODULO ID="GENERAL"/></MODULOS><ICONO URL="~/Assets/images/Icons/25/Exit.png"/></ROOT>',1), 9)
SET IDENTITY_INSERT [ADM].[C_ROL] ON
INSERT INTO [ADM].[C_ROL] ([ID_ROL], [CL_ROL], [NB_ROL], [XML_AUTORIZACION], [FG_ACTIVO], [FE_INACTIVO], [FE_CREACION], [FE_MODIFICACION], [CL_USUARIO_APP_CREA], [CL_USUARIO_APP_MODIFICA], [NB_PROGRAMA_CREA], [NB_PROGRAMA_MODIFICA]) VALUES (1, N'ADMINISTRADOR', N'Administrador', NULL, 1, NULL, '20171127 12:59:12.630', '20171228 13:35:34.457', N'JDIAZ', N'admin', N'SCRIPT INSTALACIÓN', N'/Administracion/VentanaRoles.aspx')
SET IDENTITY_INSERT [ADM].[C_ROL] OFF

INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,3)
INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,4)
INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,5)
INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,6)
INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,7)
INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,8)
INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,9)
INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,10)
INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,11)
INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,12)
INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,998)
INSERT INTO [ADM].[C_ROL_FUNCION] ([ID_ROL], [ID_FUNCION]) VALUES (1,999)

INSERT INTO [ADM].[C_USUARIO] 
VALUES('admin', 'Administrador', 'ahernandez@sigein.com.mx', '1000:LIMAZLRC+SmWjZKIT3rigHIPUk8gyizk:7gm4tJXeJYwyNGOgtGdcuJaqfLmjEc66',NULL,NULL,0,NULL,1,NULL,1, NULL, 'CORPORATIVO', GETDATE(), NULL, 'ADMIN', NULL, 'SCRIPT INSTALACION', NULL)

COMMIT TRANSACTION
