//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ACRUXLICENCIAMIENTOEntities : DbContext
    {
        public ACRUXLICENCIAMIENTOEntities()
            : base("name=ACRUXLICENCIAMIENTOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SPE_ELIMINA_C_CATALOGO_LISTA(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_CATALOGO_LISTA, string pIN_CL_USUARIO_APP_CREA, string pIN_NB_PROGRAMA_CREA)
        {
            var pIN_ID_CATALOGO_LISTAParameter = pIN_ID_CATALOGO_LISTA.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_LISTA", pIN_ID_CATALOGO_LISTA) :
                new ObjectParameter("PIN_ID_CATALOGO_LISTA", typeof(int));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_C_CATALOGO_LISTA", xML_RESULTADO, pIN_ID_CATALOGO_LISTAParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_NB_PROGRAMA_CREAParameter);
        }
    
        public virtual int SPE_ELIMINA_C_CATALOGO_VALOR(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_CATALOGO_VALOR, string pIN_CL_USUARIO_APP_CREA, string pIN_NB_PROGRAMA_CREA)
        {
            var pIN_ID_CATALOGO_VALORParameter = pIN_ID_CATALOGO_VALOR.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_VALOR", pIN_ID_CATALOGO_VALOR) :
                new ObjectParameter("PIN_ID_CATALOGO_VALOR", typeof(int));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_C_CATALOGO_VALOR", xML_RESULTADO, pIN_ID_CATALOGO_VALORParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_NB_PROGRAMA_CREAParameter);
        }
    
        public virtual int SPE_ELIMINA_C_ROL_FUNCION(ObjectParameter pOUT_CLAVE_RETORNO, Nullable<int> pIN_ID_ROL, Nullable<int> pIN_ID_FUNCION, string pIN_CL_USUARIO_APP_CREA, string pIN_NB_PROGRAMA_CREA)
        {
            var pIN_ID_ROLParameter = pIN_ID_ROL.HasValue ?
                new ObjectParameter("PIN_ID_ROL", pIN_ID_ROL) :
                new ObjectParameter("PIN_ID_ROL", typeof(int));
    
            var pIN_ID_FUNCIONParameter = pIN_ID_FUNCION.HasValue ?
                new ObjectParameter("PIN_ID_FUNCION", pIN_ID_FUNCION) :
                new ObjectParameter("PIN_ID_FUNCION", typeof(int));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_C_ROL_FUNCION", pOUT_CLAVE_RETORNO, pIN_ID_ROLParameter, pIN_ID_FUNCIONParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_NB_PROGRAMA_CREAParameter);
        }
    
        public virtual int SPE_ELIMINA_C_USUARIO(ObjectParameter xML_RESULTADO, string pIN_CL_USUARIO, string pIN_CL_USUARIO_APP_CREA, string pIN_NB_PROGRAMA_CREA)
        {
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_C_USUARIO", xML_RESULTADO, pIN_CL_USUARIOParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_NB_PROGRAMA_CREAParameter);
        }
    
        public virtual int SPE_ELIMINA_ROL(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_ROL, string pIN_CL_USUARIO_APP_CREA, string pIN_NB_PROGRAMA_CREA)
        {
            var pIN_ID_ROLParameter = pIN_ID_ROL.HasValue ?
                new ObjectParameter("PIN_ID_ROL", pIN_ID_ROL) :
                new ObjectParameter("PIN_ID_ROL", typeof(int));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_ROL", xML_RESULTADO, pIN_ID_ROLParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_NB_PROGRAMA_CREAParameter);
        }
    
        public virtual int SPE_ELIMINA_S_CATALOGO_TIPO(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_CATALOGO_TIPO, string pIN_CL_USUARIO_APP_CREA, string pIN_NB_PROGRAMA_CREA)
        {
            var pIN_ID_CATALOGO_TIPOParameter = pIN_ID_CATALOGO_TIPO.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_TIPO", pIN_ID_CATALOGO_TIPO) :
                new ObjectParameter("PIN_ID_CATALOGO_TIPO", typeof(int));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_S_CATALOGO_TIPO", xML_RESULTADO, pIN_ID_CATALOGO_TIPOParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_NB_PROGRAMA_CREAParameter);
        }
    
        public virtual int SPE_ELIMINA_S_FUNCION(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_FUNCION, string pIN_CL_USUARIO_APP_CREA, string pIN_NB_PROGRAMA_CREA)
        {
            var pIN_ID_FUNCIONParameter = pIN_ID_FUNCION.HasValue ?
                new ObjectParameter("PIN_ID_FUNCION", pIN_ID_FUNCION) :
                new ObjectParameter("PIN_ID_FUNCION", typeof(int));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_S_FUNCION", xML_RESULTADO, pIN_ID_FUNCIONParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_NB_PROGRAMA_CREAParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_C_CATALOGO_LISTA(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_CATALOGO_LISTA, string pIN_NB_CATALOGO_LISTA, string pIN_DS_CATALOGO_LISTA, Nullable<int> pIN_ID_CATALOGO_TIPO, string pIN_CL_USUARIO_APP_CREA, string pIN_CL_USUARIO_APP_MODIFICA, string pIN_NB_PROGRAMA_CREA, string pIN_NB_PROGRAMA_MODIFICA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_ID_CATALOGO_LISTAParameter = pIN_ID_CATALOGO_LISTA.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_LISTA", pIN_ID_CATALOGO_LISTA) :
                new ObjectParameter("PIN_ID_CATALOGO_LISTA", typeof(int));
    
            var pIN_NB_CATALOGO_LISTAParameter = pIN_NB_CATALOGO_LISTA != null ?
                new ObjectParameter("PIN_NB_CATALOGO_LISTA", pIN_NB_CATALOGO_LISTA) :
                new ObjectParameter("PIN_NB_CATALOGO_LISTA", typeof(string));
    
            var pIN_DS_CATALOGO_LISTAParameter = pIN_DS_CATALOGO_LISTA != null ?
                new ObjectParameter("PIN_DS_CATALOGO_LISTA", pIN_DS_CATALOGO_LISTA) :
                new ObjectParameter("PIN_DS_CATALOGO_LISTA", typeof(string));
    
            var pIN_ID_CATALOGO_TIPOParameter = pIN_ID_CATALOGO_TIPO.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_TIPO", pIN_ID_CATALOGO_TIPO) :
                new ObjectParameter("PIN_ID_CATALOGO_TIPO", typeof(int));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_CL_USUARIO_APP_MODIFICAParameter = pIN_CL_USUARIO_APP_MODIFICA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_MODIFICA", pIN_CL_USUARIO_APP_MODIFICA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_MODIFICA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_MODIFICAParameter = pIN_NB_PROGRAMA_MODIFICA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_MODIFICA", pIN_NB_PROGRAMA_MODIFICA) :
                new ObjectParameter("PIN_NB_PROGRAMA_MODIFICA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_C_CATALOGO_LISTA", xML_RESULTADO, pIN_ID_CATALOGO_LISTAParameter, pIN_NB_CATALOGO_LISTAParameter, pIN_DS_CATALOGO_LISTAParameter, pIN_ID_CATALOGO_TIPOParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_CL_USUARIO_APP_MODIFICAParameter, pIN_NB_PROGRAMA_CREAParameter, pIN_NB_PROGRAMA_MODIFICAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_C_CATALOGO_VALOR(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_CATALOGO_VALOR, string pIN_CL_CATALOGO_VALOR, string pIN_NB_CATALOGO_VALOR, string pIN_DS_CATALOGO_VALOR, Nullable<int> pIN_ID_CATALOGO_LISTA, string pIN_CL_USUARIO_APP_CREA, string pIN_CL_USUARIO_APP_MODIFICA, string pIN_NB_PROGRAMA_CREA, string pIN_NB_PROGRAMA_MODIFICA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_ID_CATALOGO_VALORParameter = pIN_ID_CATALOGO_VALOR.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_VALOR", pIN_ID_CATALOGO_VALOR) :
                new ObjectParameter("PIN_ID_CATALOGO_VALOR", typeof(int));
    
            var pIN_CL_CATALOGO_VALORParameter = pIN_CL_CATALOGO_VALOR != null ?
                new ObjectParameter("PIN_CL_CATALOGO_VALOR", pIN_CL_CATALOGO_VALOR) :
                new ObjectParameter("PIN_CL_CATALOGO_VALOR", typeof(string));
    
            var pIN_NB_CATALOGO_VALORParameter = pIN_NB_CATALOGO_VALOR != null ?
                new ObjectParameter("PIN_NB_CATALOGO_VALOR", pIN_NB_CATALOGO_VALOR) :
                new ObjectParameter("PIN_NB_CATALOGO_VALOR", typeof(string));
    
            var pIN_DS_CATALOGO_VALORParameter = pIN_DS_CATALOGO_VALOR != null ?
                new ObjectParameter("PIN_DS_CATALOGO_VALOR", pIN_DS_CATALOGO_VALOR) :
                new ObjectParameter("PIN_DS_CATALOGO_VALOR", typeof(string));
    
            var pIN_ID_CATALOGO_LISTAParameter = pIN_ID_CATALOGO_LISTA.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_LISTA", pIN_ID_CATALOGO_LISTA) :
                new ObjectParameter("PIN_ID_CATALOGO_LISTA", typeof(int));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_CL_USUARIO_APP_MODIFICAParameter = pIN_CL_USUARIO_APP_MODIFICA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_MODIFICA", pIN_CL_USUARIO_APP_MODIFICA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_MODIFICA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_MODIFICAParameter = pIN_NB_PROGRAMA_MODIFICA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_MODIFICA", pIN_NB_PROGRAMA_MODIFICA) :
                new ObjectParameter("PIN_NB_PROGRAMA_MODIFICA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_C_CATALOGO_VALOR", xML_RESULTADO, pIN_ID_CATALOGO_VALORParameter, pIN_CL_CATALOGO_VALORParameter, pIN_NB_CATALOGO_VALORParameter, pIN_DS_CATALOGO_VALORParameter, pIN_ID_CATALOGO_LISTAParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_CL_USUARIO_APP_MODIFICAParameter, pIN_NB_PROGRAMA_CREAParameter, pIN_NB_PROGRAMA_MODIFICAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_C_ROL(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_ROL, string pIN_CL_ROL, string pIN_NB_ROL, string pIN_XML_AUTORIZACION, Nullable<bool> pIN_FG_ACTIVO, Nullable<System.DateTime> pIN_FE_INACTIVO, string pIN_CL_USUARIO_APP_CREA, string pIN_CL_USUARIO_APP_MODIFICA, string pIN_NB_PROGRAMA_CREA, string pIN_NB_PROGRAMA_MODIFICA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_ID_ROLParameter = pIN_ID_ROL.HasValue ?
                new ObjectParameter("PIN_ID_ROL", pIN_ID_ROL) :
                new ObjectParameter("PIN_ID_ROL", typeof(int));
    
            var pIN_CL_ROLParameter = pIN_CL_ROL != null ?
                new ObjectParameter("PIN_CL_ROL", pIN_CL_ROL) :
                new ObjectParameter("PIN_CL_ROL", typeof(string));
    
            var pIN_NB_ROLParameter = pIN_NB_ROL != null ?
                new ObjectParameter("PIN_NB_ROL", pIN_NB_ROL) :
                new ObjectParameter("PIN_NB_ROL", typeof(string));
    
            var pIN_XML_AUTORIZACIONParameter = pIN_XML_AUTORIZACION != null ?
                new ObjectParameter("PIN_XML_AUTORIZACION", pIN_XML_AUTORIZACION) :
                new ObjectParameter("PIN_XML_AUTORIZACION", typeof(string));
    
            var pIN_FG_ACTIVOParameter = pIN_FG_ACTIVO.HasValue ?
                new ObjectParameter("PIN_FG_ACTIVO", pIN_FG_ACTIVO) :
                new ObjectParameter("PIN_FG_ACTIVO", typeof(bool));
    
            var pIN_FE_INACTIVOParameter = pIN_FE_INACTIVO.HasValue ?
                new ObjectParameter("PIN_FE_INACTIVO", pIN_FE_INACTIVO) :
                new ObjectParameter("PIN_FE_INACTIVO", typeof(System.DateTime));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_CL_USUARIO_APP_MODIFICAParameter = pIN_CL_USUARIO_APP_MODIFICA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_MODIFICA", pIN_CL_USUARIO_APP_MODIFICA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_MODIFICA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_MODIFICAParameter = pIN_NB_PROGRAMA_MODIFICA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_MODIFICA", pIN_NB_PROGRAMA_MODIFICA) :
                new ObjectParameter("PIN_NB_PROGRAMA_MODIFICA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_C_ROL", xML_RESULTADO, pIN_ID_ROLParameter, pIN_CL_ROLParameter, pIN_NB_ROLParameter, pIN_XML_AUTORIZACIONParameter, pIN_FG_ACTIVOParameter, pIN_FE_INACTIVOParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_CL_USUARIO_APP_MODIFICAParameter, pIN_NB_PROGRAMA_CREAParameter, pIN_NB_PROGRAMA_MODIFICAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_C_ROL_FUNCION(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_ROL, Nullable<int> pIN_ID_FUNCION, string pIN_TIPO_TRANSACCION, string pIN_CL_USUARIO_APP_CREA, string pIN_NB_PROGRAMA_CREA)
        {
            var pIN_ID_ROLParameter = pIN_ID_ROL.HasValue ?
                new ObjectParameter("PIN_ID_ROL", pIN_ID_ROL) :
                new ObjectParameter("PIN_ID_ROL", typeof(int));
    
            var pIN_ID_FUNCIONParameter = pIN_ID_FUNCION.HasValue ?
                new ObjectParameter("PIN_ID_FUNCION", pIN_ID_FUNCION) :
                new ObjectParameter("PIN_ID_FUNCION", typeof(int));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_C_ROL_FUNCION", xML_RESULTADO, pIN_ID_ROLParameter, pIN_ID_FUNCIONParameter, pIN_TIPO_TRANSACCIONParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_NB_PROGRAMA_CREAParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_C_USUARIO(ObjectParameter xML_RESULTADO, string pIN_CL_USUARIO, string pIN_NB_USUARIO, string pIN_NB_CORREO_ELECTRONICO, string pIN_NB_PASSWORD, Nullable<bool> pIN_FG_CAMBIAR_PASSWORD, string pIN_XML_PERSONALIZACION, Nullable<int> pIN_ID_ROL, Nullable<int> pIN_ID_EMPLEADO, Nullable<bool> pIN_FG_ACTIVO, Nullable<System.DateTime> pIN_FE_INACTIVO, string pIN_CL_USUARIO_APP_CREA, string pIN_CL_USUARIO_APP_MODIFICA, string pIN_NB_PROGRAMA_CREA, string pIN_NB_PROGRAMA_MODIFICA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_NB_USUARIOParameter = pIN_NB_USUARIO != null ?
                new ObjectParameter("PIN_NB_USUARIO", pIN_NB_USUARIO) :
                new ObjectParameter("PIN_NB_USUARIO", typeof(string));
    
            var pIN_NB_CORREO_ELECTRONICOParameter = pIN_NB_CORREO_ELECTRONICO != null ?
                new ObjectParameter("PIN_NB_CORREO_ELECTRONICO", pIN_NB_CORREO_ELECTRONICO) :
                new ObjectParameter("PIN_NB_CORREO_ELECTRONICO", typeof(string));
    
            var pIN_NB_PASSWORDParameter = pIN_NB_PASSWORD != null ?
                new ObjectParameter("PIN_NB_PASSWORD", pIN_NB_PASSWORD) :
                new ObjectParameter("PIN_NB_PASSWORD", typeof(string));
    
            var pIN_FG_CAMBIAR_PASSWORDParameter = pIN_FG_CAMBIAR_PASSWORD.HasValue ?
                new ObjectParameter("PIN_FG_CAMBIAR_PASSWORD", pIN_FG_CAMBIAR_PASSWORD) :
                new ObjectParameter("PIN_FG_CAMBIAR_PASSWORD", typeof(bool));
    
            var pIN_XML_PERSONALIZACIONParameter = pIN_XML_PERSONALIZACION != null ?
                new ObjectParameter("PIN_XML_PERSONALIZACION", pIN_XML_PERSONALIZACION) :
                new ObjectParameter("PIN_XML_PERSONALIZACION", typeof(string));
    
            var pIN_ID_ROLParameter = pIN_ID_ROL.HasValue ?
                new ObjectParameter("PIN_ID_ROL", pIN_ID_ROL) :
                new ObjectParameter("PIN_ID_ROL", typeof(int));
    
            var pIN_ID_EMPLEADOParameter = pIN_ID_EMPLEADO.HasValue ?
                new ObjectParameter("PIN_ID_EMPLEADO", pIN_ID_EMPLEADO) :
                new ObjectParameter("PIN_ID_EMPLEADO", typeof(int));
    
            var pIN_FG_ACTIVOParameter = pIN_FG_ACTIVO.HasValue ?
                new ObjectParameter("PIN_FG_ACTIVO", pIN_FG_ACTIVO) :
                new ObjectParameter("PIN_FG_ACTIVO", typeof(bool));
    
            var pIN_FE_INACTIVOParameter = pIN_FE_INACTIVO.HasValue ?
                new ObjectParameter("PIN_FE_INACTIVO", pIN_FE_INACTIVO) :
                new ObjectParameter("PIN_FE_INACTIVO", typeof(System.DateTime));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_CL_USUARIO_APP_MODIFICAParameter = pIN_CL_USUARIO_APP_MODIFICA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_MODIFICA", pIN_CL_USUARIO_APP_MODIFICA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_MODIFICA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_MODIFICAParameter = pIN_NB_PROGRAMA_MODIFICA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_MODIFICA", pIN_NB_PROGRAMA_MODIFICA) :
                new ObjectParameter("PIN_NB_PROGRAMA_MODIFICA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_C_USUARIO", xML_RESULTADO, pIN_CL_USUARIOParameter, pIN_NB_USUARIOParameter, pIN_NB_CORREO_ELECTRONICOParameter, pIN_NB_PASSWORDParameter, pIN_FG_CAMBIAR_PASSWORDParameter, pIN_XML_PERSONALIZACIONParameter, pIN_ID_ROLParameter, pIN_ID_EMPLEADOParameter, pIN_FG_ACTIVOParameter, pIN_FE_INACTIVOParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_CL_USUARIO_APP_MODIFICAParameter, pIN_NB_PROGRAMA_CREAParameter, pIN_NB_PROGRAMA_MODIFICAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_S_CATALOGO_TIPO(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_CATALOGO_TIPO, string pIN_NB_CATALOGO_TIPO, string pIN_DS_CATALOGO_TIPO, string pIN_TIPO_TRANSACCION, string pIN_CL_USUARIO_APP_CREA, string pIN_NB_PROGRAMA_CREA)
        {
            var pIN_ID_CATALOGO_TIPOParameter = pIN_ID_CATALOGO_TIPO.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_TIPO", pIN_ID_CATALOGO_TIPO) :
                new ObjectParameter("PIN_ID_CATALOGO_TIPO", typeof(int));
    
            var pIN_NB_CATALOGO_TIPOParameter = pIN_NB_CATALOGO_TIPO != null ?
                new ObjectParameter("PIN_NB_CATALOGO_TIPO", pIN_NB_CATALOGO_TIPO) :
                new ObjectParameter("PIN_NB_CATALOGO_TIPO", typeof(string));
    
            var pIN_DS_CATALOGO_TIPOParameter = pIN_DS_CATALOGO_TIPO != null ?
                new ObjectParameter("PIN_DS_CATALOGO_TIPO", pIN_DS_CATALOGO_TIPO) :
                new ObjectParameter("PIN_DS_CATALOGO_TIPO", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_S_CATALOGO_TIPO", xML_RESULTADO, pIN_ID_CATALOGO_TIPOParameter, pIN_NB_CATALOGO_TIPOParameter, pIN_DS_CATALOGO_TIPOParameter, pIN_TIPO_TRANSACCIONParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_NB_PROGRAMA_CREAParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_S_CONFIGURACION(ObjectParameter xML_RESULTADO, string pIN_XML_CONFIGURACION, byte[] pIN_FI_LOGOTIPO, string pIN_CL_USUARIO_MODIFICA, string pIN_NB_PROGRAMA_MODIFICA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_XML_CONFIGURACIONParameter = pIN_XML_CONFIGURACION != null ?
                new ObjectParameter("PIN_XML_CONFIGURACION", pIN_XML_CONFIGURACION) :
                new ObjectParameter("PIN_XML_CONFIGURACION", typeof(string));
    
            var pIN_FI_LOGOTIPOParameter = pIN_FI_LOGOTIPO != null ?
                new ObjectParameter("PIN_FI_LOGOTIPO", pIN_FI_LOGOTIPO) :
                new ObjectParameter("PIN_FI_LOGOTIPO", typeof(byte[]));
    
            var pIN_CL_USUARIO_MODIFICAParameter = pIN_CL_USUARIO_MODIFICA != null ?
                new ObjectParameter("PIN_CL_USUARIO_MODIFICA", pIN_CL_USUARIO_MODIFICA) :
                new ObjectParameter("PIN_CL_USUARIO_MODIFICA", typeof(string));
    
            var pIN_NB_PROGRAMA_MODIFICAParameter = pIN_NB_PROGRAMA_MODIFICA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_MODIFICA", pIN_NB_PROGRAMA_MODIFICA) :
                new ObjectParameter("PIN_NB_PROGRAMA_MODIFICA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_S_CONFIGURACION", xML_RESULTADO, pIN_XML_CONFIGURACIONParameter, pIN_FI_LOGOTIPOParameter, pIN_CL_USUARIO_MODIFICAParameter, pIN_NB_PROGRAMA_MODIFICAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_S_FUNCION(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_FUNCION, string pIN_CL_FUNCION, string pIN_CL_TIPO_FUNCION, string pIN_NB_FUNCION, Nullable<int> pIN_ID_FUNCION_PADRE, string pIN_NB_URL, string pIN_XML_CONFIGURACION, string pIN_TIPO_TRANSACCION, string pIN_CL_USUARIO_APP_CREA, string pIN_NB_PROGRAMA_CREA)
        {
            var pIN_ID_FUNCIONParameter = pIN_ID_FUNCION.HasValue ?
                new ObjectParameter("PIN_ID_FUNCION", pIN_ID_FUNCION) :
                new ObjectParameter("PIN_ID_FUNCION", typeof(int));
    
            var pIN_CL_FUNCIONParameter = pIN_CL_FUNCION != null ?
                new ObjectParameter("PIN_CL_FUNCION", pIN_CL_FUNCION) :
                new ObjectParameter("PIN_CL_FUNCION", typeof(string));
    
            var pIN_CL_TIPO_FUNCIONParameter = pIN_CL_TIPO_FUNCION != null ?
                new ObjectParameter("PIN_CL_TIPO_FUNCION", pIN_CL_TIPO_FUNCION) :
                new ObjectParameter("PIN_CL_TIPO_FUNCION", typeof(string));
    
            var pIN_NB_FUNCIONParameter = pIN_NB_FUNCION != null ?
                new ObjectParameter("PIN_NB_FUNCION", pIN_NB_FUNCION) :
                new ObjectParameter("PIN_NB_FUNCION", typeof(string));
    
            var pIN_ID_FUNCION_PADREParameter = pIN_ID_FUNCION_PADRE.HasValue ?
                new ObjectParameter("PIN_ID_FUNCION_PADRE", pIN_ID_FUNCION_PADRE) :
                new ObjectParameter("PIN_ID_FUNCION_PADRE", typeof(int));
    
            var pIN_NB_URLParameter = pIN_NB_URL != null ?
                new ObjectParameter("PIN_NB_URL", pIN_NB_URL) :
                new ObjectParameter("PIN_NB_URL", typeof(string));
    
            var pIN_XML_CONFIGURACIONParameter = pIN_XML_CONFIGURACION != null ?
                new ObjectParameter("PIN_XML_CONFIGURACION", pIN_XML_CONFIGURACION) :
                new ObjectParameter("PIN_XML_CONFIGURACION", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_S_FUNCION", xML_RESULTADO, pIN_ID_FUNCIONParameter, pIN_CL_FUNCIONParameter, pIN_CL_TIPO_FUNCIONParameter, pIN_NB_FUNCIONParameter, pIN_ID_FUNCION_PADREParameter, pIN_NB_URLParameter, pIN_XML_CONFIGURACIONParameter, pIN_TIPO_TRANSACCIONParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_NB_PROGRAMA_CREAParameter);
        }
    
        public virtual int SPE_INSERTA_S_ERROR(Nullable<int> pIN_CL_CLAVE, string pIN_DS_ERROR, string pIN_CL_USUARIO_APP_CREA, string pIN_NB_PROGRAMA_CREA)
        {
            var pIN_CL_CLAVEParameter = pIN_CL_CLAVE.HasValue ?
                new ObjectParameter("PIN_CL_CLAVE", pIN_CL_CLAVE) :
                new ObjectParameter("PIN_CL_CLAVE", typeof(int));
    
            var pIN_DS_ERRORParameter = pIN_DS_ERROR != null ?
                new ObjectParameter("PIN_DS_ERROR", pIN_DS_ERROR) :
                new ObjectParameter("PIN_DS_ERROR", typeof(string));
    
            var pIN_CL_USUARIO_APP_CREAParameter = pIN_CL_USUARIO_APP_CREA != null ?
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", pIN_CL_USUARIO_APP_CREA) :
                new ObjectParameter("PIN_CL_USUARIO_APP_CREA", typeof(string));
    
            var pIN_NB_PROGRAMA_CREAParameter = pIN_NB_PROGRAMA_CREA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", pIN_NB_PROGRAMA_CREA) :
                new ObjectParameter("PIN_NB_PROGRAMA_CREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_S_ERROR", pIN_CL_CLAVEParameter, pIN_DS_ERRORParameter, pIN_CL_USUARIO_APP_CREAParameter, pIN_NB_PROGRAMA_CREAParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_C_CATALOGO_LISTA_Result> SPE_OBTIENE_C_CATALOGO_LISTA(Nullable<int> pIN_ID_CATALOGO_LISTA, string pIN_NB_CATALOGO_LISTA, string pIN_DS_CATALOGO_LISTA, Nullable<int> pIN_ID_CATALOGO_TIPO)
        {
            var pIN_ID_CATALOGO_LISTAParameter = pIN_ID_CATALOGO_LISTA.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_LISTA", pIN_ID_CATALOGO_LISTA) :
                new ObjectParameter("PIN_ID_CATALOGO_LISTA", typeof(int));
    
            var pIN_NB_CATALOGO_LISTAParameter = pIN_NB_CATALOGO_LISTA != null ?
                new ObjectParameter("PIN_NB_CATALOGO_LISTA", pIN_NB_CATALOGO_LISTA) :
                new ObjectParameter("PIN_NB_CATALOGO_LISTA", typeof(string));
    
            var pIN_DS_CATALOGO_LISTAParameter = pIN_DS_CATALOGO_LISTA != null ?
                new ObjectParameter("PIN_DS_CATALOGO_LISTA", pIN_DS_CATALOGO_LISTA) :
                new ObjectParameter("PIN_DS_CATALOGO_LISTA", typeof(string));
    
            var pIN_ID_CATALOGO_TIPOParameter = pIN_ID_CATALOGO_TIPO.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_TIPO", pIN_ID_CATALOGO_TIPO) :
                new ObjectParameter("PIN_ID_CATALOGO_TIPO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_C_CATALOGO_LISTA_Result>("SPE_OBTIENE_C_CATALOGO_LISTA", pIN_ID_CATALOGO_LISTAParameter, pIN_NB_CATALOGO_LISTAParameter, pIN_DS_CATALOGO_LISTAParameter, pIN_ID_CATALOGO_TIPOParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_C_CATALOGO_VALOR_Result> SPE_OBTIENE_C_CATALOGO_VALOR(Nullable<int> pIN_ID_CATALOGO_VALOR, string pIN_CL_CATALOGO_VALOR, string pIN_NB_CATALOGO_VALOR, string pIN_DS_CATALOGO_VALOR, Nullable<int> pIN_ID_CATALOGO_LISTA)
        {
            var pIN_ID_CATALOGO_VALORParameter = pIN_ID_CATALOGO_VALOR.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_VALOR", pIN_ID_CATALOGO_VALOR) :
                new ObjectParameter("PIN_ID_CATALOGO_VALOR", typeof(int));
    
            var pIN_CL_CATALOGO_VALORParameter = pIN_CL_CATALOGO_VALOR != null ?
                new ObjectParameter("PIN_CL_CATALOGO_VALOR", pIN_CL_CATALOGO_VALOR) :
                new ObjectParameter("PIN_CL_CATALOGO_VALOR", typeof(string));
    
            var pIN_NB_CATALOGO_VALORParameter = pIN_NB_CATALOGO_VALOR != null ?
                new ObjectParameter("PIN_NB_CATALOGO_VALOR", pIN_NB_CATALOGO_VALOR) :
                new ObjectParameter("PIN_NB_CATALOGO_VALOR", typeof(string));
    
            var pIN_DS_CATALOGO_VALORParameter = pIN_DS_CATALOGO_VALOR != null ?
                new ObjectParameter("PIN_DS_CATALOGO_VALOR", pIN_DS_CATALOGO_VALOR) :
                new ObjectParameter("PIN_DS_CATALOGO_VALOR", typeof(string));
    
            var pIN_ID_CATALOGO_LISTAParameter = pIN_ID_CATALOGO_LISTA.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_LISTA", pIN_ID_CATALOGO_LISTA) :
                new ObjectParameter("PIN_ID_CATALOGO_LISTA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_C_CATALOGO_VALOR_Result>("SPE_OBTIENE_C_CATALOGO_VALOR", pIN_ID_CATALOGO_VALORParameter, pIN_CL_CATALOGO_VALORParameter, pIN_NB_CATALOGO_VALORParameter, pIN_DS_CATALOGO_VALORParameter, pIN_ID_CATALOGO_LISTAParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_C_ROL_Result> SPE_OBTIENE_C_ROL(Nullable<int> pIN_ID_ROL, string pIN_CL_ROL, string pIN_NB_ROL, string pIN_XML_AUTORIZACION, Nullable<bool> pIN_FG_ACTIVO, Nullable<System.DateTime> pIN_FE_INACTIVO)
        {
            var pIN_ID_ROLParameter = pIN_ID_ROL.HasValue ?
                new ObjectParameter("PIN_ID_ROL", pIN_ID_ROL) :
                new ObjectParameter("PIN_ID_ROL", typeof(int));
    
            var pIN_CL_ROLParameter = pIN_CL_ROL != null ?
                new ObjectParameter("PIN_CL_ROL", pIN_CL_ROL) :
                new ObjectParameter("PIN_CL_ROL", typeof(string));
    
            var pIN_NB_ROLParameter = pIN_NB_ROL != null ?
                new ObjectParameter("PIN_NB_ROL", pIN_NB_ROL) :
                new ObjectParameter("PIN_NB_ROL", typeof(string));
    
            var pIN_XML_AUTORIZACIONParameter = pIN_XML_AUTORIZACION != null ?
                new ObjectParameter("PIN_XML_AUTORIZACION", pIN_XML_AUTORIZACION) :
                new ObjectParameter("PIN_XML_AUTORIZACION", typeof(string));
    
            var pIN_FG_ACTIVOParameter = pIN_FG_ACTIVO.HasValue ?
                new ObjectParameter("PIN_FG_ACTIVO", pIN_FG_ACTIVO) :
                new ObjectParameter("PIN_FG_ACTIVO", typeof(bool));
    
            var pIN_FE_INACTIVOParameter = pIN_FE_INACTIVO.HasValue ?
                new ObjectParameter("PIN_FE_INACTIVO", pIN_FE_INACTIVO) :
                new ObjectParameter("PIN_FE_INACTIVO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_C_ROL_Result>("SPE_OBTIENE_C_ROL", pIN_ID_ROLParameter, pIN_CL_ROLParameter, pIN_NB_ROLParameter, pIN_XML_AUTORIZACIONParameter, pIN_FG_ACTIVOParameter, pIN_FE_INACTIVOParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_C_ROL_FUNCION_Result> SPE_OBTIENE_C_ROL_FUNCION(Nullable<int> pIN_ID_ROL, Nullable<int> pIN_ID_FUNCION)
        {
            var pIN_ID_ROLParameter = pIN_ID_ROL.HasValue ?
                new ObjectParameter("PIN_ID_ROL", pIN_ID_ROL) :
                new ObjectParameter("PIN_ID_ROL", typeof(int));
    
            var pIN_ID_FUNCIONParameter = pIN_ID_FUNCION.HasValue ?
                new ObjectParameter("PIN_ID_FUNCION", pIN_ID_FUNCION) :
                new ObjectParameter("PIN_ID_FUNCION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_C_ROL_FUNCION_Result>("SPE_OBTIENE_C_ROL_FUNCION", pIN_ID_ROLParameter, pIN_ID_FUNCIONParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_C_USUARIO_Result> SPE_OBTIENE_C_USUARIO(string pIN_CL_USUARIO, string pIN_NB_USUARIO, string pIN_NB_CORREO_ELECTRONICO, string pIN_NB_PASSWORD, Nullable<bool> pIN_FG_CAMBIAR_PASSWORD, string pIN_XML_PERSONALIZACION, Nullable<int> pIN_ID_ROL, Nullable<int> pIN_ID_EMPLEADO, Nullable<bool> pIN_FG_ACTIVO, Nullable<System.DateTime> pIN_FE_INACTIVO)
        {
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_NB_USUARIOParameter = pIN_NB_USUARIO != null ?
                new ObjectParameter("PIN_NB_USUARIO", pIN_NB_USUARIO) :
                new ObjectParameter("PIN_NB_USUARIO", typeof(string));
    
            var pIN_NB_CORREO_ELECTRONICOParameter = pIN_NB_CORREO_ELECTRONICO != null ?
                new ObjectParameter("PIN_NB_CORREO_ELECTRONICO", pIN_NB_CORREO_ELECTRONICO) :
                new ObjectParameter("PIN_NB_CORREO_ELECTRONICO", typeof(string));
    
            var pIN_NB_PASSWORDParameter = pIN_NB_PASSWORD != null ?
                new ObjectParameter("PIN_NB_PASSWORD", pIN_NB_PASSWORD) :
                new ObjectParameter("PIN_NB_PASSWORD", typeof(string));
    
            var pIN_FG_CAMBIAR_PASSWORDParameter = pIN_FG_CAMBIAR_PASSWORD.HasValue ?
                new ObjectParameter("PIN_FG_CAMBIAR_PASSWORD", pIN_FG_CAMBIAR_PASSWORD) :
                new ObjectParameter("PIN_FG_CAMBIAR_PASSWORD", typeof(bool));
    
            var pIN_XML_PERSONALIZACIONParameter = pIN_XML_PERSONALIZACION != null ?
                new ObjectParameter("PIN_XML_PERSONALIZACION", pIN_XML_PERSONALIZACION) :
                new ObjectParameter("PIN_XML_PERSONALIZACION", typeof(string));
    
            var pIN_ID_ROLParameter = pIN_ID_ROL.HasValue ?
                new ObjectParameter("PIN_ID_ROL", pIN_ID_ROL) :
                new ObjectParameter("PIN_ID_ROL", typeof(int));
    
            var pIN_ID_EMPLEADOParameter = pIN_ID_EMPLEADO.HasValue ?
                new ObjectParameter("PIN_ID_EMPLEADO", pIN_ID_EMPLEADO) :
                new ObjectParameter("PIN_ID_EMPLEADO", typeof(int));
    
            var pIN_FG_ACTIVOParameter = pIN_FG_ACTIVO.HasValue ?
                new ObjectParameter("PIN_FG_ACTIVO", pIN_FG_ACTIVO) :
                new ObjectParameter("PIN_FG_ACTIVO", typeof(bool));
    
            var pIN_FE_INACTIVOParameter = pIN_FE_INACTIVO.HasValue ?
                new ObjectParameter("PIN_FE_INACTIVO", pIN_FE_INACTIVO) :
                new ObjectParameter("PIN_FE_INACTIVO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_C_USUARIO_Result>("SPE_OBTIENE_C_USUARIO", pIN_CL_USUARIOParameter, pIN_NB_USUARIOParameter, pIN_NB_CORREO_ELECTRONICOParameter, pIN_NB_PASSWORDParameter, pIN_FG_CAMBIAR_PASSWORDParameter, pIN_XML_PERSONALIZACIONParameter, pIN_ID_ROLParameter, pIN_ID_EMPLEADOParameter, pIN_FG_ACTIVOParameter, pIN_FE_INACTIVOParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_S_CATALOGO_TIPO_Result> SPE_OBTIENE_S_CATALOGO_TIPO(Nullable<int> pIN_ID_CATALOGO_TIPO, string pIN_NB_CATALOGO_TIPO, string pIN_DS_CATALOGO_TIPO)
        {
            var pIN_ID_CATALOGO_TIPOParameter = pIN_ID_CATALOGO_TIPO.HasValue ?
                new ObjectParameter("PIN_ID_CATALOGO_TIPO", pIN_ID_CATALOGO_TIPO) :
                new ObjectParameter("PIN_ID_CATALOGO_TIPO", typeof(int));
    
            var pIN_NB_CATALOGO_TIPOParameter = pIN_NB_CATALOGO_TIPO != null ?
                new ObjectParameter("PIN_NB_CATALOGO_TIPO", pIN_NB_CATALOGO_TIPO) :
                new ObjectParameter("PIN_NB_CATALOGO_TIPO", typeof(string));
    
            var pIN_DS_CATALOGO_TIPOParameter = pIN_DS_CATALOGO_TIPO != null ?
                new ObjectParameter("PIN_DS_CATALOGO_TIPO", pIN_DS_CATALOGO_TIPO) :
                new ObjectParameter("PIN_DS_CATALOGO_TIPO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_S_CATALOGO_TIPO_Result>("SPE_OBTIENE_S_CATALOGO_TIPO", pIN_ID_CATALOGO_TIPOParameter, pIN_NB_CATALOGO_TIPOParameter, pIN_DS_CATALOGO_TIPOParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_S_CONFIGURACION_Result> SPE_OBTIENE_S_CONFIGURACION(string pIN_XML_CONFIGURACION, string pIN_CL_USUARIO_MODIFICA)
        {
            var pIN_XML_CONFIGURACIONParameter = pIN_XML_CONFIGURACION != null ?
                new ObjectParameter("PIN_XML_CONFIGURACION", pIN_XML_CONFIGURACION) :
                new ObjectParameter("PIN_XML_CONFIGURACION", typeof(string));
    
            var pIN_CL_USUARIO_MODIFICAParameter = pIN_CL_USUARIO_MODIFICA != null ?
                new ObjectParameter("PIN_CL_USUARIO_MODIFICA", pIN_CL_USUARIO_MODIFICA) :
                new ObjectParameter("PIN_CL_USUARIO_MODIFICA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_S_CONFIGURACION_Result>("SPE_OBTIENE_S_CONFIGURACION", pIN_XML_CONFIGURACIONParameter, pIN_CL_USUARIO_MODIFICAParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_S_FUNCION_Result> SPE_OBTIENE_S_FUNCION(Nullable<int> pIN_ID_FUNCION, string pIN_CL_FUNCION, string pIN_CL_TIPO_FUNCION, string pIN_NB_FUNCION, Nullable<int> pIN_ID_FUNCION_PADRE, string pIN_NB_URL, string pIN_XML_CONFIGURACION)
        {
            var pIN_ID_FUNCIONParameter = pIN_ID_FUNCION.HasValue ?
                new ObjectParameter("PIN_ID_FUNCION", pIN_ID_FUNCION) :
                new ObjectParameter("PIN_ID_FUNCION", typeof(int));
    
            var pIN_CL_FUNCIONParameter = pIN_CL_FUNCION != null ?
                new ObjectParameter("PIN_CL_FUNCION", pIN_CL_FUNCION) :
                new ObjectParameter("PIN_CL_FUNCION", typeof(string));
    
            var pIN_CL_TIPO_FUNCIONParameter = pIN_CL_TIPO_FUNCION != null ?
                new ObjectParameter("PIN_CL_TIPO_FUNCION", pIN_CL_TIPO_FUNCION) :
                new ObjectParameter("PIN_CL_TIPO_FUNCION", typeof(string));
    
            var pIN_NB_FUNCIONParameter = pIN_NB_FUNCION != null ?
                new ObjectParameter("PIN_NB_FUNCION", pIN_NB_FUNCION) :
                new ObjectParameter("PIN_NB_FUNCION", typeof(string));
    
            var pIN_ID_FUNCION_PADREParameter = pIN_ID_FUNCION_PADRE.HasValue ?
                new ObjectParameter("PIN_ID_FUNCION_PADRE", pIN_ID_FUNCION_PADRE) :
                new ObjectParameter("PIN_ID_FUNCION_PADRE", typeof(int));
    
            var pIN_NB_URLParameter = pIN_NB_URL != null ?
                new ObjectParameter("PIN_NB_URL", pIN_NB_URL) :
                new ObjectParameter("PIN_NB_URL", typeof(string));
    
            var pIN_XML_CONFIGURACIONParameter = pIN_XML_CONFIGURACION != null ?
                new ObjectParameter("PIN_XML_CONFIGURACION", pIN_XML_CONFIGURACION) :
                new ObjectParameter("PIN_XML_CONFIGURACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_S_FUNCION_Result>("SPE_OBTIENE_S_FUNCION", pIN_ID_FUNCIONParameter, pIN_CL_FUNCIONParameter, pIN_CL_TIPO_FUNCIONParameter, pIN_NB_FUNCIONParameter, pIN_ID_FUNCION_PADREParameter, pIN_NB_URLParameter, pIN_XML_CONFIGURACIONParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_USUARIO_AUTENTICACION_Result> SPE_OBTIENE_USUARIO_AUTENTICACION(string pIN_CL_USUARIO, string pIN_CL_PASSWORD, string pIN_CL_AUTENTICACION)
        {
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_CL_PASSWORDParameter = pIN_CL_PASSWORD != null ?
                new ObjectParameter("PIN_CL_PASSWORD", pIN_CL_PASSWORD) :
                new ObjectParameter("PIN_CL_PASSWORD", typeof(string));
    
            var pIN_CL_AUTENTICACIONParameter = pIN_CL_AUTENTICACION != null ?
                new ObjectParameter("PIN_CL_AUTENTICACION", pIN_CL_AUTENTICACION) :
                new ObjectParameter("PIN_CL_AUTENTICACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_USUARIO_AUTENTICACION_Result>("SPE_OBTIENE_USUARIO_AUTENTICACION", pIN_CL_USUARIOParameter, pIN_CL_PASSWORDParameter, pIN_CL_AUTENTICACIONParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_ROLES_Result> SPE_OBTIENE_ROLES(Nullable<int> pIN_ID_ROL)
        {
            var pIN_ID_ROLParameter = pIN_ID_ROL.HasValue ?
                new ObjectParameter("PIN_ID_ROL", pIN_ID_ROL) :
                new ObjectParameter("PIN_ID_ROL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_ROLES_Result>("SPE_OBTIENE_ROLES", pIN_ID_ROLParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_ROL_Result> SPE_OBTIENE_ROL(Nullable<int> pIN_ID_ROL)
        {
            var pIN_ID_ROLParameter = pIN_ID_ROL.HasValue ?
                new ObjectParameter("PIN_ID_ROL", pIN_ID_ROL) :
                new ObjectParameter("PIN_ID_ROL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_ROL_Result>("SPE_OBTIENE_ROL", pIN_ID_ROLParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_ROLES(ObjectParameter xML_RESULTADO, Nullable<int> pIN_ID_ROL, string pIN_CL_ROL, string pIN_NB_ROL, Nullable<bool> pIN_FG_ACTIVO, string pIN_XML_FUNCIONES, string pIN_CL_USUARIO, string pIN_NB_PROGRAMA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_ID_ROLParameter = pIN_ID_ROL.HasValue ?
                new ObjectParameter("PIN_ID_ROL", pIN_ID_ROL) :
                new ObjectParameter("PIN_ID_ROL", typeof(int));
    
            var pIN_CL_ROLParameter = pIN_CL_ROL != null ?
                new ObjectParameter("PIN_CL_ROL", pIN_CL_ROL) :
                new ObjectParameter("PIN_CL_ROL", typeof(string));
    
            var pIN_NB_ROLParameter = pIN_NB_ROL != null ?
                new ObjectParameter("PIN_NB_ROL", pIN_NB_ROL) :
                new ObjectParameter("PIN_NB_ROL", typeof(string));
    
            var pIN_FG_ACTIVOParameter = pIN_FG_ACTIVO.HasValue ?
                new ObjectParameter("PIN_FG_ACTIVO", pIN_FG_ACTIVO) :
                new ObjectParameter("PIN_FG_ACTIVO", typeof(bool));
    
            var pIN_XML_FUNCIONESParameter = pIN_XML_FUNCIONES != null ?
                new ObjectParameter("PIN_XML_FUNCIONES", pIN_XML_FUNCIONES) :
                new ObjectParameter("PIN_XML_FUNCIONES", typeof(string));
    
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_NB_PROGRAMAParameter = pIN_NB_PROGRAMA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA", pIN_NB_PROGRAMA) :
                new ObjectParameter("PIN_NB_PROGRAMA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_ROLES", xML_RESULTADO, pIN_ID_ROLParameter, pIN_CL_ROLParameter, pIN_NB_ROLParameter, pIN_FG_ACTIVOParameter, pIN_XML_FUNCIONESParameter, pIN_CL_USUARIOParameter, pIN_NB_PROGRAMAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual int SPE_ELIMINA_C_CLIENTE(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_CLIENTE)
        {
            var pIN_ID_CLIENTEParameter = pIN_ID_CLIENTE.HasValue ?
                new ObjectParameter("PIN_ID_CLIENTE", pIN_ID_CLIENTE) :
                new ObjectParameter("PIN_ID_CLIENTE", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_C_CLIENTE", xML_RESULTADO, pIN_ID_CLIENTEParameter);
        }
    
        public virtual int SPE_ELIMINA_C_EMPRESA(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_EMPRESA)
        {
            var pIN_ID_EMPRESAParameter = pIN_ID_EMPRESA.HasValue ?
                new ObjectParameter("PIN_ID_EMPRESA", pIN_ID_EMPRESA) :
                new ObjectParameter("PIN_ID_EMPRESA", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_C_EMPRESA", xML_RESULTADO, pIN_ID_EMPRESAParameter);
        }
    
        public virtual int SPE_ELIMINA_C_LICENCIA(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_LICENCIA)
        {
            var pIN_ID_LICENCIAParameter = pIN_ID_LICENCIA.HasValue ?
                new ObjectParameter("PIN_ID_LICENCIA", pIN_ID_LICENCIA) :
                new ObjectParameter("PIN_ID_LICENCIA", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_C_LICENCIA", xML_RESULTADO, pIN_ID_LICENCIAParameter);
        }
    
        public virtual int SPE_ELIMINA_C_MODULO(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_MODULO)
        {
            var pIN_ID_MODULOParameter = pIN_ID_MODULO.HasValue ?
                new ObjectParameter("PIN_ID_MODULO", pIN_ID_MODULO) :
                new ObjectParameter("PIN_ID_MODULO", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_C_MODULO", xML_RESULTADO, pIN_ID_MODULOParameter);
        }
    
        public virtual int SPE_ELIMINA_C_SISTEMA(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_SISTEMA)
        {
            var pIN_ID_SISTEMAParameter = pIN_ID_SISTEMA.HasValue ?
                new ObjectParameter("PIN_ID_SISTEMA", pIN_ID_SISTEMA) :
                new ObjectParameter("PIN_ID_SISTEMA", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_C_SISTEMA", xML_RESULTADO, pIN_ID_SISTEMAParameter);
        }
    
        public virtual int SPE_ELIMINA_C_VERSION(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_VERSION)
        {
            var pIN_ID_VERSIONParameter = pIN_ID_VERSION.HasValue ?
                new ObjectParameter("PIN_ID_VERSION", pIN_ID_VERSION) :
                new ObjectParameter("PIN_ID_VERSION", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_C_VERSION", xML_RESULTADO, pIN_ID_VERSIONParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_C_EMPRESA(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_EMPRESA, string pIN_CL_EMPRESA, string pIN_NB_EMPRESA, string pIN_DS_EMPRESA, string pIN_CL_USUARIO, string pIN_NB_PROGRAMA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_ID_EMPRESAParameter = pIN_ID_EMPRESA.HasValue ?
                new ObjectParameter("PIN_ID_EMPRESA", pIN_ID_EMPRESA) :
                new ObjectParameter("PIN_ID_EMPRESA", typeof(System.Guid));
    
            var pIN_CL_EMPRESAParameter = pIN_CL_EMPRESA != null ?
                new ObjectParameter("PIN_CL_EMPRESA", pIN_CL_EMPRESA) :
                new ObjectParameter("PIN_CL_EMPRESA", typeof(string));
    
            var pIN_NB_EMPRESAParameter = pIN_NB_EMPRESA != null ?
                new ObjectParameter("PIN_NB_EMPRESA", pIN_NB_EMPRESA) :
                new ObjectParameter("PIN_NB_EMPRESA", typeof(string));
    
            var pIN_DS_EMPRESAParameter = pIN_DS_EMPRESA != null ?
                new ObjectParameter("PIN_DS_EMPRESA", pIN_DS_EMPRESA) :
                new ObjectParameter("PIN_DS_EMPRESA", typeof(string));
    
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_NB_PROGRAMAParameter = pIN_NB_PROGRAMA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA", pIN_NB_PROGRAMA) :
                new ObjectParameter("PIN_NB_PROGRAMA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_C_EMPRESA", xML_RESULTADO, pIN_ID_EMPRESAParameter, pIN_CL_EMPRESAParameter, pIN_NB_EMPRESAParameter, pIN_DS_EMPRESAParameter, pIN_CL_USUARIOParameter, pIN_NB_PROGRAMAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_C_LICENCIA(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_LICENCIA, string pIN_CL_LICENCIA, string pIN_NB_LICENCIA, Nullable<bool> pIN_FG_PERIODO, Nullable<bool> pIN_FG_VOLUMEN, string pIN_DS_LICENCIA, string pIN_CL_USUARIO, string pIN_NB_PROGRAMA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_ID_LICENCIAParameter = pIN_ID_LICENCIA.HasValue ?
                new ObjectParameter("PIN_ID_LICENCIA", pIN_ID_LICENCIA) :
                new ObjectParameter("PIN_ID_LICENCIA", typeof(System.Guid));
    
            var pIN_CL_LICENCIAParameter = pIN_CL_LICENCIA != null ?
                new ObjectParameter("PIN_CL_LICENCIA", pIN_CL_LICENCIA) :
                new ObjectParameter("PIN_CL_LICENCIA", typeof(string));
    
            var pIN_NB_LICENCIAParameter = pIN_NB_LICENCIA != null ?
                new ObjectParameter("PIN_NB_LICENCIA", pIN_NB_LICENCIA) :
                new ObjectParameter("PIN_NB_LICENCIA", typeof(string));
    
            var pIN_FG_PERIODOParameter = pIN_FG_PERIODO.HasValue ?
                new ObjectParameter("PIN_FG_PERIODO", pIN_FG_PERIODO) :
                new ObjectParameter("PIN_FG_PERIODO", typeof(bool));
    
            var pIN_FG_VOLUMENParameter = pIN_FG_VOLUMEN.HasValue ?
                new ObjectParameter("PIN_FG_VOLUMEN", pIN_FG_VOLUMEN) :
                new ObjectParameter("PIN_FG_VOLUMEN", typeof(bool));
    
            var pIN_DS_LICENCIAParameter = pIN_DS_LICENCIA != null ?
                new ObjectParameter("PIN_DS_LICENCIA", pIN_DS_LICENCIA) :
                new ObjectParameter("PIN_DS_LICENCIA", typeof(string));
    
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_NB_PROGRAMAParameter = pIN_NB_PROGRAMA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA", pIN_NB_PROGRAMA) :
                new ObjectParameter("PIN_NB_PROGRAMA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_C_LICENCIA", xML_RESULTADO, pIN_ID_LICENCIAParameter, pIN_CL_LICENCIAParameter, pIN_NB_LICENCIAParameter, pIN_FG_PERIODOParameter, pIN_FG_VOLUMENParameter, pIN_DS_LICENCIAParameter, pIN_CL_USUARIOParameter, pIN_NB_PROGRAMAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_C_MODULO(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_MODULO, string pIN_CL_MODULO, string pIN_NB_MODULO, string pIN_DS_MODULO, Nullable<System.Guid> pIN_ID_SISTEMA, string pIN_CL_USUARIO, string pIN_NB_PROGRAMA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_ID_MODULOParameter = pIN_ID_MODULO.HasValue ?
                new ObjectParameter("PIN_ID_MODULO", pIN_ID_MODULO) :
                new ObjectParameter("PIN_ID_MODULO", typeof(System.Guid));
    
            var pIN_CL_MODULOParameter = pIN_CL_MODULO != null ?
                new ObjectParameter("PIN_CL_MODULO", pIN_CL_MODULO) :
                new ObjectParameter("PIN_CL_MODULO", typeof(string));
    
            var pIN_NB_MODULOParameter = pIN_NB_MODULO != null ?
                new ObjectParameter("PIN_NB_MODULO", pIN_NB_MODULO) :
                new ObjectParameter("PIN_NB_MODULO", typeof(string));
    
            var pIN_DS_MODULOParameter = pIN_DS_MODULO != null ?
                new ObjectParameter("PIN_DS_MODULO", pIN_DS_MODULO) :
                new ObjectParameter("PIN_DS_MODULO", typeof(string));
    
            var pIN_ID_SISTEMAParameter = pIN_ID_SISTEMA.HasValue ?
                new ObjectParameter("PIN_ID_SISTEMA", pIN_ID_SISTEMA) :
                new ObjectParameter("PIN_ID_SISTEMA", typeof(System.Guid));
    
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_NB_PROGRAMAParameter = pIN_NB_PROGRAMA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA", pIN_NB_PROGRAMA) :
                new ObjectParameter("PIN_NB_PROGRAMA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_C_MODULO", xML_RESULTADO, pIN_ID_MODULOParameter, pIN_CL_MODULOParameter, pIN_NB_MODULOParameter, pIN_DS_MODULOParameter, pIN_ID_SISTEMAParameter, pIN_CL_USUARIOParameter, pIN_NB_PROGRAMAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_C_SISTEMA(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_SISTEMA, string pIN_CL_SISTEMA, string pIN_NB_SISTEMA, string pIN_CL_TIPO, string pIN_DS_SISTEMA, string pIN_CL_USUARIO, string pIN_NB_PROGRAMA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_ID_SISTEMAParameter = pIN_ID_SISTEMA.HasValue ?
                new ObjectParameter("PIN_ID_SISTEMA", pIN_ID_SISTEMA) :
                new ObjectParameter("PIN_ID_SISTEMA", typeof(System.Guid));
    
            var pIN_CL_SISTEMAParameter = pIN_CL_SISTEMA != null ?
                new ObjectParameter("PIN_CL_SISTEMA", pIN_CL_SISTEMA) :
                new ObjectParameter("PIN_CL_SISTEMA", typeof(string));
    
            var pIN_NB_SISTEMAParameter = pIN_NB_SISTEMA != null ?
                new ObjectParameter("PIN_NB_SISTEMA", pIN_NB_SISTEMA) :
                new ObjectParameter("PIN_NB_SISTEMA", typeof(string));
    
            var pIN_CL_TIPOParameter = pIN_CL_TIPO != null ?
                new ObjectParameter("PIN_CL_TIPO", pIN_CL_TIPO) :
                new ObjectParameter("PIN_CL_TIPO", typeof(string));
    
            var pIN_DS_SISTEMAParameter = pIN_DS_SISTEMA != null ?
                new ObjectParameter("PIN_DS_SISTEMA", pIN_DS_SISTEMA) :
                new ObjectParameter("PIN_DS_SISTEMA", typeof(string));
    
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_NB_PROGRAMAParameter = pIN_NB_PROGRAMA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA", pIN_NB_PROGRAMA) :
                new ObjectParameter("PIN_NB_PROGRAMA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_C_SISTEMA", xML_RESULTADO, pIN_ID_SISTEMAParameter, pIN_CL_SISTEMAParameter, pIN_NB_SISTEMAParameter, pIN_CL_TIPOParameter, pIN_DS_SISTEMAParameter, pIN_CL_USUARIOParameter, pIN_NB_PROGRAMAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_C_VERSION(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_VERSION, Nullable<System.Guid> pIN_ID_MODULO, Nullable<decimal> pIN_NO_RELEASE, string pIN_DS_VERSION, string pIN_CL_USUARIO, string pIN_NB_PROGRAMA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_ID_VERSIONParameter = pIN_ID_VERSION.HasValue ?
                new ObjectParameter("PIN_ID_VERSION", pIN_ID_VERSION) :
                new ObjectParameter("PIN_ID_VERSION", typeof(System.Guid));
    
            var pIN_ID_MODULOParameter = pIN_ID_MODULO.HasValue ?
                new ObjectParameter("PIN_ID_MODULO", pIN_ID_MODULO) :
                new ObjectParameter("PIN_ID_MODULO", typeof(System.Guid));
    
            var pIN_NO_RELEASEParameter = pIN_NO_RELEASE.HasValue ?
                new ObjectParameter("PIN_NO_RELEASE", pIN_NO_RELEASE) :
                new ObjectParameter("PIN_NO_RELEASE", typeof(decimal));
    
            var pIN_DS_VERSIONParameter = pIN_DS_VERSION != null ?
                new ObjectParameter("PIN_DS_VERSION", pIN_DS_VERSION) :
                new ObjectParameter("PIN_DS_VERSION", typeof(string));
    
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_NB_PROGRAMAParameter = pIN_NB_PROGRAMA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA", pIN_NB_PROGRAMA) :
                new ObjectParameter("PIN_NB_PROGRAMA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_C_VERSION", xML_RESULTADO, pIN_ID_VERSIONParameter, pIN_ID_MODULOParameter, pIN_NO_RELEASEParameter, pIN_DS_VERSIONParameter, pIN_CL_USUARIOParameter, pIN_NB_PROGRAMAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_C_EMPRESA_Result> SPE_OBTIENE_C_EMPRESA(Nullable<System.Guid> pIN_ID_EMPRESA, string pIN_CL_EMPRESA, string pIN_NB_EMPRESA, string pIN_DS_EMPRESA)
        {
            var pIN_ID_EMPRESAParameter = pIN_ID_EMPRESA.HasValue ?
                new ObjectParameter("PIN_ID_EMPRESA", pIN_ID_EMPRESA) :
                new ObjectParameter("PIN_ID_EMPRESA", typeof(System.Guid));
    
            var pIN_CL_EMPRESAParameter = pIN_CL_EMPRESA != null ?
                new ObjectParameter("PIN_CL_EMPRESA", pIN_CL_EMPRESA) :
                new ObjectParameter("PIN_CL_EMPRESA", typeof(string));
    
            var pIN_NB_EMPRESAParameter = pIN_NB_EMPRESA != null ?
                new ObjectParameter("PIN_NB_EMPRESA", pIN_NB_EMPRESA) :
                new ObjectParameter("PIN_NB_EMPRESA", typeof(string));
    
            var pIN_DS_EMPRESAParameter = pIN_DS_EMPRESA != null ?
                new ObjectParameter("PIN_DS_EMPRESA", pIN_DS_EMPRESA) :
                new ObjectParameter("PIN_DS_EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_C_EMPRESA_Result>("SPE_OBTIENE_C_EMPRESA", pIN_ID_EMPRESAParameter, pIN_CL_EMPRESAParameter, pIN_NB_EMPRESAParameter, pIN_DS_EMPRESAParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_C_LICENCIA_Result> SPE_OBTIENE_C_LICENCIA(Nullable<System.Guid> pIN_ID_LICENCIA, string pIN_CL_LICENCIA, string pIN_NB_LICENCIA, Nullable<bool> pIN_FG_PERIODO, Nullable<bool> pIN_FG_VOLUMEN, string pIN_DS_LICENCIA)
        {
            var pIN_ID_LICENCIAParameter = pIN_ID_LICENCIA.HasValue ?
                new ObjectParameter("PIN_ID_LICENCIA", pIN_ID_LICENCIA) :
                new ObjectParameter("PIN_ID_LICENCIA", typeof(System.Guid));
    
            var pIN_CL_LICENCIAParameter = pIN_CL_LICENCIA != null ?
                new ObjectParameter("PIN_CL_LICENCIA", pIN_CL_LICENCIA) :
                new ObjectParameter("PIN_CL_LICENCIA", typeof(string));
    
            var pIN_NB_LICENCIAParameter = pIN_NB_LICENCIA != null ?
                new ObjectParameter("PIN_NB_LICENCIA", pIN_NB_LICENCIA) :
                new ObjectParameter("PIN_NB_LICENCIA", typeof(string));
    
            var pIN_FG_PERIODOParameter = pIN_FG_PERIODO.HasValue ?
                new ObjectParameter("PIN_FG_PERIODO", pIN_FG_PERIODO) :
                new ObjectParameter("PIN_FG_PERIODO", typeof(bool));
    
            var pIN_FG_VOLUMENParameter = pIN_FG_VOLUMEN.HasValue ?
                new ObjectParameter("PIN_FG_VOLUMEN", pIN_FG_VOLUMEN) :
                new ObjectParameter("PIN_FG_VOLUMEN", typeof(bool));
    
            var pIN_DS_LICENCIAParameter = pIN_DS_LICENCIA != null ?
                new ObjectParameter("PIN_DS_LICENCIA", pIN_DS_LICENCIA) :
                new ObjectParameter("PIN_DS_LICENCIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_C_LICENCIA_Result>("SPE_OBTIENE_C_LICENCIA", pIN_ID_LICENCIAParameter, pIN_CL_LICENCIAParameter, pIN_NB_LICENCIAParameter, pIN_FG_PERIODOParameter, pIN_FG_VOLUMENParameter, pIN_DS_LICENCIAParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_C_MODULO_Result> SPE_OBTIENE_C_MODULO(Nullable<System.Guid> pIN_ID_MODULO, string pIN_CL_MODULO, string pIN_NB_MODULO, string pIN_DS_MODULO, Nullable<System.Guid> pIN_ID_SISTEMA, string pIN_CL_SISTEMA, string pIN_NB_SISTEMA)
        {
            var pIN_ID_MODULOParameter = pIN_ID_MODULO.HasValue ?
                new ObjectParameter("PIN_ID_MODULO", pIN_ID_MODULO) :
                new ObjectParameter("PIN_ID_MODULO", typeof(System.Guid));
    
            var pIN_CL_MODULOParameter = pIN_CL_MODULO != null ?
                new ObjectParameter("PIN_CL_MODULO", pIN_CL_MODULO) :
                new ObjectParameter("PIN_CL_MODULO", typeof(string));
    
            var pIN_NB_MODULOParameter = pIN_NB_MODULO != null ?
                new ObjectParameter("PIN_NB_MODULO", pIN_NB_MODULO) :
                new ObjectParameter("PIN_NB_MODULO", typeof(string));
    
            var pIN_DS_MODULOParameter = pIN_DS_MODULO != null ?
                new ObjectParameter("PIN_DS_MODULO", pIN_DS_MODULO) :
                new ObjectParameter("PIN_DS_MODULO", typeof(string));
    
            var pIN_ID_SISTEMAParameter = pIN_ID_SISTEMA.HasValue ?
                new ObjectParameter("PIN_ID_SISTEMA", pIN_ID_SISTEMA) :
                new ObjectParameter("PIN_ID_SISTEMA", typeof(System.Guid));
    
            var pIN_CL_SISTEMAParameter = pIN_CL_SISTEMA != null ?
                new ObjectParameter("PIN_CL_SISTEMA", pIN_CL_SISTEMA) :
                new ObjectParameter("PIN_CL_SISTEMA", typeof(string));
    
            var pIN_NB_SISTEMAParameter = pIN_NB_SISTEMA != null ?
                new ObjectParameter("PIN_NB_SISTEMA", pIN_NB_SISTEMA) :
                new ObjectParameter("PIN_NB_SISTEMA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_C_MODULO_Result>("SPE_OBTIENE_C_MODULO", pIN_ID_MODULOParameter, pIN_CL_MODULOParameter, pIN_NB_MODULOParameter, pIN_DS_MODULOParameter, pIN_ID_SISTEMAParameter, pIN_CL_SISTEMAParameter, pIN_NB_SISTEMAParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_C_SISTEMA_Result> SPE_OBTIENE_C_SISTEMA(Nullable<System.Guid> pIN_ID_SISTEMA, string pIN_CL_SISTEMA, string pIN_NB_SISTEMA, string pIN_CL_TIPO, string pIN_DS_SISTEMA)
        {
            var pIN_ID_SISTEMAParameter = pIN_ID_SISTEMA.HasValue ?
                new ObjectParameter("PIN_ID_SISTEMA", pIN_ID_SISTEMA) :
                new ObjectParameter("PIN_ID_SISTEMA", typeof(System.Guid));
    
            var pIN_CL_SISTEMAParameter = pIN_CL_SISTEMA != null ?
                new ObjectParameter("PIN_CL_SISTEMA", pIN_CL_SISTEMA) :
                new ObjectParameter("PIN_CL_SISTEMA", typeof(string));
    
            var pIN_NB_SISTEMAParameter = pIN_NB_SISTEMA != null ?
                new ObjectParameter("PIN_NB_SISTEMA", pIN_NB_SISTEMA) :
                new ObjectParameter("PIN_NB_SISTEMA", typeof(string));
    
            var pIN_CL_TIPOParameter = pIN_CL_TIPO != null ?
                new ObjectParameter("PIN_CL_TIPO", pIN_CL_TIPO) :
                new ObjectParameter("PIN_CL_TIPO", typeof(string));
    
            var pIN_DS_SISTEMAParameter = pIN_DS_SISTEMA != null ?
                new ObjectParameter("PIN_DS_SISTEMA", pIN_DS_SISTEMA) :
                new ObjectParameter("PIN_DS_SISTEMA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_C_SISTEMA_Result>("SPE_OBTIENE_C_SISTEMA", pIN_ID_SISTEMAParameter, pIN_CL_SISTEMAParameter, pIN_NB_SISTEMAParameter, pIN_CL_TIPOParameter, pIN_DS_SISTEMAParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_C_VERSION_Result> SPE_OBTIENE_C_VERSION(Nullable<System.Guid> pIN_ID_VERSION, Nullable<System.Guid> pIN_ID_MODULO, Nullable<decimal> pIN_NO_RELEASE, string pIN_DS_VERSION)
        {
            var pIN_ID_VERSIONParameter = pIN_ID_VERSION.HasValue ?
                new ObjectParameter("PIN_ID_VERSION", pIN_ID_VERSION) :
                new ObjectParameter("PIN_ID_VERSION", typeof(System.Guid));
    
            var pIN_ID_MODULOParameter = pIN_ID_MODULO.HasValue ?
                new ObjectParameter("PIN_ID_MODULO", pIN_ID_MODULO) :
                new ObjectParameter("PIN_ID_MODULO", typeof(System.Guid));
    
            var pIN_NO_RELEASEParameter = pIN_NO_RELEASE.HasValue ?
                new ObjectParameter("PIN_NO_RELEASE", pIN_NO_RELEASE) :
                new ObjectParameter("PIN_NO_RELEASE", typeof(decimal));
    
            var pIN_DS_VERSIONParameter = pIN_DS_VERSION != null ?
                new ObjectParameter("PIN_DS_VERSION", pIN_DS_VERSION) :
                new ObjectParameter("PIN_DS_VERSION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_C_VERSION_Result>("SPE_OBTIENE_C_VERSION", pIN_ID_VERSIONParameter, pIN_ID_MODULOParameter, pIN_NO_RELEASEParameter, pIN_DS_VERSIONParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_K_GESTION_PERIODO(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_GESTION_PERIODO, Nullable<System.Guid> pIN_ID_CLIENTE, Nullable<System.Guid> pIN_ID_SISTEMA, Nullable<System.Guid> pIN_ID_EMPRESA, Nullable<System.Guid> pIN_ID_MODULO, Nullable<System.Guid> pIN_ID_VERSION, Nullable<System.Guid> pIN_ID_LICENCIA, Nullable<System.DateTime> pIN_FE_INICIO, Nullable<System.DateTime> pIN_FE_FIN, Nullable<int> pIN_NO_VOLUMEN, string pIN_CL_USUARIO, string pIN_NB_PROGRAMA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_ID_GESTION_PERIODOParameter = pIN_ID_GESTION_PERIODO.HasValue ?
                new ObjectParameter("PIN_ID_GESTION_PERIODO", pIN_ID_GESTION_PERIODO) :
                new ObjectParameter("PIN_ID_GESTION_PERIODO", typeof(System.Guid));
    
            var pIN_ID_CLIENTEParameter = pIN_ID_CLIENTE.HasValue ?
                new ObjectParameter("PIN_ID_CLIENTE", pIN_ID_CLIENTE) :
                new ObjectParameter("PIN_ID_CLIENTE", typeof(System.Guid));
    
            var pIN_ID_SISTEMAParameter = pIN_ID_SISTEMA.HasValue ?
                new ObjectParameter("PIN_ID_SISTEMA", pIN_ID_SISTEMA) :
                new ObjectParameter("PIN_ID_SISTEMA", typeof(System.Guid));
    
            var pIN_ID_EMPRESAParameter = pIN_ID_EMPRESA.HasValue ?
                new ObjectParameter("PIN_ID_EMPRESA", pIN_ID_EMPRESA) :
                new ObjectParameter("PIN_ID_EMPRESA", typeof(System.Guid));
    
            var pIN_ID_MODULOParameter = pIN_ID_MODULO.HasValue ?
                new ObjectParameter("PIN_ID_MODULO", pIN_ID_MODULO) :
                new ObjectParameter("PIN_ID_MODULO", typeof(System.Guid));
    
            var pIN_ID_VERSIONParameter = pIN_ID_VERSION.HasValue ?
                new ObjectParameter("PIN_ID_VERSION", pIN_ID_VERSION) :
                new ObjectParameter("PIN_ID_VERSION", typeof(System.Guid));
    
            var pIN_ID_LICENCIAParameter = pIN_ID_LICENCIA.HasValue ?
                new ObjectParameter("PIN_ID_LICENCIA", pIN_ID_LICENCIA) :
                new ObjectParameter("PIN_ID_LICENCIA", typeof(System.Guid));
    
            var pIN_FE_INICIOParameter = pIN_FE_INICIO.HasValue ?
                new ObjectParameter("PIN_FE_INICIO", pIN_FE_INICIO) :
                new ObjectParameter("PIN_FE_INICIO", typeof(System.DateTime));
    
            var pIN_FE_FINParameter = pIN_FE_FIN.HasValue ?
                new ObjectParameter("PIN_FE_FIN", pIN_FE_FIN) :
                new ObjectParameter("PIN_FE_FIN", typeof(System.DateTime));
    
            var pIN_NO_VOLUMENParameter = pIN_NO_VOLUMEN.HasValue ?
                new ObjectParameter("PIN_NO_VOLUMEN", pIN_NO_VOLUMEN) :
                new ObjectParameter("PIN_NO_VOLUMEN", typeof(int));
    
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_NB_PROGRAMAParameter = pIN_NB_PROGRAMA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA", pIN_NB_PROGRAMA) :
                new ObjectParameter("PIN_NB_PROGRAMA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_K_GESTION_PERIODO", xML_RESULTADO, pIN_ID_GESTION_PERIODOParameter, pIN_ID_CLIENTEParameter, pIN_ID_SISTEMAParameter, pIN_ID_EMPRESAParameter, pIN_ID_MODULOParameter, pIN_ID_VERSIONParameter, pIN_ID_LICENCIAParameter, pIN_FE_INICIOParameter, pIN_FE_FINParameter, pIN_NO_VOLUMENParameter, pIN_CL_USUARIOParameter, pIN_NB_PROGRAMAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_K_GESTION_PERIODOS_Result> SPE_OBTIENE_K_GESTION_PERIODOS(Nullable<System.Guid> pIN_ID_GESTION_PERIODO, Nullable<System.Guid> pIN_ID_CLIENTE, Nullable<System.Guid> pIN_ID_SISTEMA, Nullable<System.Guid> pIN_ID_EMPRESA, Nullable<System.Guid> pIN_ID_MODULO, Nullable<System.Guid> pIN_ID_VERSION, Nullable<System.Guid> pIN_ID_LICENCIA, Nullable<System.DateTime> pIN_FE_INICIO, Nullable<System.DateTime> pIN_FE_FIN, Nullable<int> pIN_NO_VOLUMEN)
        {
            var pIN_ID_GESTION_PERIODOParameter = pIN_ID_GESTION_PERIODO.HasValue ?
                new ObjectParameter("PIN_ID_GESTION_PERIODO", pIN_ID_GESTION_PERIODO) :
                new ObjectParameter("PIN_ID_GESTION_PERIODO", typeof(System.Guid));
    
            var pIN_ID_CLIENTEParameter = pIN_ID_CLIENTE.HasValue ?
                new ObjectParameter("PIN_ID_CLIENTE", pIN_ID_CLIENTE) :
                new ObjectParameter("PIN_ID_CLIENTE", typeof(System.Guid));
    
            var pIN_ID_SISTEMAParameter = pIN_ID_SISTEMA.HasValue ?
                new ObjectParameter("PIN_ID_SISTEMA", pIN_ID_SISTEMA) :
                new ObjectParameter("PIN_ID_SISTEMA", typeof(System.Guid));
    
            var pIN_ID_EMPRESAParameter = pIN_ID_EMPRESA.HasValue ?
                new ObjectParameter("PIN_ID_EMPRESA", pIN_ID_EMPRESA) :
                new ObjectParameter("PIN_ID_EMPRESA", typeof(System.Guid));
    
            var pIN_ID_MODULOParameter = pIN_ID_MODULO.HasValue ?
                new ObjectParameter("PIN_ID_MODULO", pIN_ID_MODULO) :
                new ObjectParameter("PIN_ID_MODULO", typeof(System.Guid));
    
            var pIN_ID_VERSIONParameter = pIN_ID_VERSION.HasValue ?
                new ObjectParameter("PIN_ID_VERSION", pIN_ID_VERSION) :
                new ObjectParameter("PIN_ID_VERSION", typeof(System.Guid));
    
            var pIN_ID_LICENCIAParameter = pIN_ID_LICENCIA.HasValue ?
                new ObjectParameter("PIN_ID_LICENCIA", pIN_ID_LICENCIA) :
                new ObjectParameter("PIN_ID_LICENCIA", typeof(System.Guid));
    
            var pIN_FE_INICIOParameter = pIN_FE_INICIO.HasValue ?
                new ObjectParameter("PIN_FE_INICIO", pIN_FE_INICIO) :
                new ObjectParameter("PIN_FE_INICIO", typeof(System.DateTime));
    
            var pIN_FE_FINParameter = pIN_FE_FIN.HasValue ?
                new ObjectParameter("PIN_FE_FIN", pIN_FE_FIN) :
                new ObjectParameter("PIN_FE_FIN", typeof(System.DateTime));
    
            var pIN_NO_VOLUMENParameter = pIN_NO_VOLUMEN.HasValue ?
                new ObjectParameter("PIN_NO_VOLUMEN", pIN_NO_VOLUMEN) :
                new ObjectParameter("PIN_NO_VOLUMEN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_K_GESTION_PERIODOS_Result>("SPE_OBTIENE_K_GESTION_PERIODOS", pIN_ID_GESTION_PERIODOParameter, pIN_ID_CLIENTEParameter, pIN_ID_SISTEMAParameter, pIN_ID_EMPRESAParameter, pIN_ID_MODULOParameter, pIN_ID_VERSIONParameter, pIN_ID_LICENCIAParameter, pIN_FE_INICIOParameter, pIN_FE_FINParameter, pIN_NO_VOLUMENParameter);
        }
    
        public virtual int SPE_ELIMINA_K_GESTION_PERIODO(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_GESTION_PERIODO)
        {
            var pIN_ID_GESTION_PERIODOParameter = pIN_ID_GESTION_PERIODO.HasValue ?
                new ObjectParameter("PIN_ID_GESTION_PERIODO", pIN_ID_GESTION_PERIODO) :
                new ObjectParameter("PIN_ID_GESTION_PERIODO", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_ELIMINA_K_GESTION_PERIODO", xML_RESULTADO, pIN_ID_GESTION_PERIODOParameter);
        }
    
        public virtual int SPE_INSERTA_ACTUALIZA_C_CLIENTE(ObjectParameter xML_RESULTADO, Nullable<System.Guid> pIN_ID_CLIENTE, string pIN_CL_CLIENTE, string pIN_CL_PASSWORD, string pIN_NB_CLIENTE, string pIN_NB_CONTACTO, string pIN_CL_EMAIL, string pIN_XML_TELEFONOS, string pIN_XML_EMPRESAS, string pIN_NB_EJECUTIVO_CUENTA, string pIN_CL_USUARIO, string pIN_NB_PROGRAMA, string pIN_TIPO_TRANSACCION)
        {
            var pIN_ID_CLIENTEParameter = pIN_ID_CLIENTE.HasValue ?
                new ObjectParameter("PIN_ID_CLIENTE", pIN_ID_CLIENTE) :
                new ObjectParameter("PIN_ID_CLIENTE", typeof(System.Guid));
    
            var pIN_CL_CLIENTEParameter = pIN_CL_CLIENTE != null ?
                new ObjectParameter("PIN_CL_CLIENTE", pIN_CL_CLIENTE) :
                new ObjectParameter("PIN_CL_CLIENTE", typeof(string));
    
            var pIN_CL_PASSWORDParameter = pIN_CL_PASSWORD != null ?
                new ObjectParameter("PIN_CL_PASSWORD", pIN_CL_PASSWORD) :
                new ObjectParameter("PIN_CL_PASSWORD", typeof(string));
    
            var pIN_NB_CLIENTEParameter = pIN_NB_CLIENTE != null ?
                new ObjectParameter("PIN_NB_CLIENTE", pIN_NB_CLIENTE) :
                new ObjectParameter("PIN_NB_CLIENTE", typeof(string));
    
            var pIN_NB_CONTACTOParameter = pIN_NB_CONTACTO != null ?
                new ObjectParameter("PIN_NB_CONTACTO", pIN_NB_CONTACTO) :
                new ObjectParameter("PIN_NB_CONTACTO", typeof(string));
    
            var pIN_CL_EMAILParameter = pIN_CL_EMAIL != null ?
                new ObjectParameter("PIN_CL_EMAIL", pIN_CL_EMAIL) :
                new ObjectParameter("PIN_CL_EMAIL", typeof(string));
    
            var pIN_XML_TELEFONOSParameter = pIN_XML_TELEFONOS != null ?
                new ObjectParameter("PIN_XML_TELEFONOS", pIN_XML_TELEFONOS) :
                new ObjectParameter("PIN_XML_TELEFONOS", typeof(string));
    
            var pIN_XML_EMPRESASParameter = pIN_XML_EMPRESAS != null ?
                new ObjectParameter("PIN_XML_EMPRESAS", pIN_XML_EMPRESAS) :
                new ObjectParameter("PIN_XML_EMPRESAS", typeof(string));
    
            var pIN_NB_EJECUTIVO_CUENTAParameter = pIN_NB_EJECUTIVO_CUENTA != null ?
                new ObjectParameter("PIN_NB_EJECUTIVO_CUENTA", pIN_NB_EJECUTIVO_CUENTA) :
                new ObjectParameter("PIN_NB_EJECUTIVO_CUENTA", typeof(string));
    
            var pIN_CL_USUARIOParameter = pIN_CL_USUARIO != null ?
                new ObjectParameter("PIN_CL_USUARIO", pIN_CL_USUARIO) :
                new ObjectParameter("PIN_CL_USUARIO", typeof(string));
    
            var pIN_NB_PROGRAMAParameter = pIN_NB_PROGRAMA != null ?
                new ObjectParameter("PIN_NB_PROGRAMA", pIN_NB_PROGRAMA) :
                new ObjectParameter("PIN_NB_PROGRAMA", typeof(string));
    
            var pIN_TIPO_TRANSACCIONParameter = pIN_TIPO_TRANSACCION != null ?
                new ObjectParameter("PIN_TIPO_TRANSACCION", pIN_TIPO_TRANSACCION) :
                new ObjectParameter("PIN_TIPO_TRANSACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPE_INSERTA_ACTUALIZA_C_CLIENTE", xML_RESULTADO, pIN_ID_CLIENTEParameter, pIN_CL_CLIENTEParameter, pIN_CL_PASSWORDParameter, pIN_NB_CLIENTEParameter, pIN_NB_CONTACTOParameter, pIN_CL_EMAILParameter, pIN_XML_TELEFONOSParameter, pIN_XML_EMPRESASParameter, pIN_NB_EJECUTIVO_CUENTAParameter, pIN_CL_USUARIOParameter, pIN_NB_PROGRAMAParameter, pIN_TIPO_TRANSACCIONParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_LICENCIAMIENTO_Result> SPE_OBTIENE_LICENCIAMIENTO(string pIN_CL_CLIENTE, string pIN_CL_PASSWORD, string pIN_CL_SISTEMA, string pIN_CL_EMPRESA, string pIN_CL_MODULO, Nullable<decimal> pIN_NO_VERSION, string pIN_CL_LICENCIA)
        {
            var pIN_CL_CLIENTEParameter = pIN_CL_CLIENTE != null ?
                new ObjectParameter("PIN_CL_CLIENTE", pIN_CL_CLIENTE) :
                new ObjectParameter("PIN_CL_CLIENTE", typeof(string));
    
            var pIN_CL_PASSWORDParameter = pIN_CL_PASSWORD != null ?
                new ObjectParameter("PIN_CL_PASSWORD", pIN_CL_PASSWORD) :
                new ObjectParameter("PIN_CL_PASSWORD", typeof(string));
    
            var pIN_CL_SISTEMAParameter = pIN_CL_SISTEMA != null ?
                new ObjectParameter("PIN_CL_SISTEMA", pIN_CL_SISTEMA) :
                new ObjectParameter("PIN_CL_SISTEMA", typeof(string));
    
            var pIN_CL_EMPRESAParameter = pIN_CL_EMPRESA != null ?
                new ObjectParameter("PIN_CL_EMPRESA", pIN_CL_EMPRESA) :
                new ObjectParameter("PIN_CL_EMPRESA", typeof(string));
    
            var pIN_CL_MODULOParameter = pIN_CL_MODULO != null ?
                new ObjectParameter("PIN_CL_MODULO", pIN_CL_MODULO) :
                new ObjectParameter("PIN_CL_MODULO", typeof(string));
    
            var pIN_NO_VERSIONParameter = pIN_NO_VERSION.HasValue ?
                new ObjectParameter("PIN_NO_VERSION", pIN_NO_VERSION) :
                new ObjectParameter("PIN_NO_VERSION", typeof(decimal));
    
            var pIN_CL_LICENCIAParameter = pIN_CL_LICENCIA != null ?
                new ObjectParameter("PIN_CL_LICENCIA", pIN_CL_LICENCIA) :
                new ObjectParameter("PIN_CL_LICENCIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_LICENCIAMIENTO_Result>("SPE_OBTIENE_LICENCIAMIENTO", pIN_CL_CLIENTEParameter, pIN_CL_PASSWORDParameter, pIN_CL_SISTEMAParameter, pIN_CL_EMPRESAParameter, pIN_CL_MODULOParameter, pIN_NO_VERSIONParameter, pIN_CL_LICENCIAParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_C_CLIENTES_Result> SPE_OBTIENE_C_CLIENTES(Nullable<System.Guid> pIN_ID_CLIENTE, string pIN_CL_CLIENTE, string pIN_CL_PASSWORD, string pIN_NB_CLIENTE, string pIN_NB_CONTACTO, string pIN_CL_EMAIL, string pIN_NB_EJECUTIVO_CUENTA)
        {
            var pIN_ID_CLIENTEParameter = pIN_ID_CLIENTE.HasValue ?
                new ObjectParameter("PIN_ID_CLIENTE", pIN_ID_CLIENTE) :
                new ObjectParameter("PIN_ID_CLIENTE", typeof(System.Guid));
    
            var pIN_CL_CLIENTEParameter = pIN_CL_CLIENTE != null ?
                new ObjectParameter("PIN_CL_CLIENTE", pIN_CL_CLIENTE) :
                new ObjectParameter("PIN_CL_CLIENTE", typeof(string));
    
            var pIN_CL_PASSWORDParameter = pIN_CL_PASSWORD != null ?
                new ObjectParameter("PIN_CL_PASSWORD", pIN_CL_PASSWORD) :
                new ObjectParameter("PIN_CL_PASSWORD", typeof(string));
    
            var pIN_NB_CLIENTEParameter = pIN_NB_CLIENTE != null ?
                new ObjectParameter("PIN_NB_CLIENTE", pIN_NB_CLIENTE) :
                new ObjectParameter("PIN_NB_CLIENTE", typeof(string));
    
            var pIN_NB_CONTACTOParameter = pIN_NB_CONTACTO != null ?
                new ObjectParameter("PIN_NB_CONTACTO", pIN_NB_CONTACTO) :
                new ObjectParameter("PIN_NB_CONTACTO", typeof(string));
    
            var pIN_CL_EMAILParameter = pIN_CL_EMAIL != null ?
                new ObjectParameter("PIN_CL_EMAIL", pIN_CL_EMAIL) :
                new ObjectParameter("PIN_CL_EMAIL", typeof(string));
    
            var pIN_NB_EJECUTIVO_CUENTAParameter = pIN_NB_EJECUTIVO_CUENTA != null ?
                new ObjectParameter("PIN_NB_EJECUTIVO_CUENTA", pIN_NB_EJECUTIVO_CUENTA) :
                new ObjectParameter("PIN_NB_EJECUTIVO_CUENTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_C_CLIENTES_Result>("SPE_OBTIENE_C_CLIENTES", pIN_ID_CLIENTEParameter, pIN_CL_CLIENTEParameter, pIN_CL_PASSWORDParameter, pIN_NB_CLIENTEParameter, pIN_NB_CONTACTOParameter, pIN_CL_EMAILParameter, pIN_NB_EJECUTIVO_CUENTAParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_CLIENTE_CATALOGOS_Result> SPE_OBTIENE_CLIENTE_CATALOGOS(Nullable<System.Guid> pIN_ID_CLIENTE)
        {
            var pIN_ID_CLIENTEParameter = pIN_ID_CLIENTE.HasValue ?
                new ObjectParameter("PIN_ID_CLIENTE", pIN_ID_CLIENTE) :
                new ObjectParameter("PIN_ID_CLIENTE", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_CLIENTE_CATALOGOS_Result>("SPE_OBTIENE_CLIENTE_CATALOGOS", pIN_ID_CLIENTEParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_INFORMACION_CLIENTE_Result> SPE_OBTIENE_INFORMACION_CLIENTE(string pIN_CL_CLIENTE, string pIN_CL_PASSWORD)
        {
            var pIN_CL_CLIENTEParameter = pIN_CL_CLIENTE != null ?
                new ObjectParameter("PIN_CL_CLIENTE", pIN_CL_CLIENTE) :
                new ObjectParameter("PIN_CL_CLIENTE", typeof(string));
    
            var pIN_CL_PASSWORDParameter = pIN_CL_PASSWORD != null ?
                new ObjectParameter("PIN_CL_PASSWORD", pIN_CL_PASSWORD) :
                new ObjectParameter("PIN_CL_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_INFORMACION_CLIENTE_Result>("SPE_OBTIENE_INFORMACION_CLIENTE", pIN_CL_CLIENTEParameter, pIN_CL_PASSWORDParameter);
        }
    
        public virtual ObjectResult<SPE_OBTIENE_LICENCIAS_Result> SPE_OBTIENE_LICENCIAS(string pIN_CL_CLIENTE, string pIN_CL_PASSWORD)
        {
            var pIN_CL_CLIENTEParameter = pIN_CL_CLIENTE != null ?
                new ObjectParameter("PIN_CL_CLIENTE", pIN_CL_CLIENTE) :
                new ObjectParameter("PIN_CL_CLIENTE", typeof(string));
    
            var pIN_CL_PASSWORDParameter = pIN_CL_PASSWORD != null ?
                new ObjectParameter("PIN_CL_PASSWORD", pIN_CL_PASSWORD) :
                new ObjectParameter("PIN_CL_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_OBTIENE_LICENCIAS_Result>("SPE_OBTIENE_LICENCIAS", pIN_CL_CLIENTEParameter, pIN_CL_PASSWORDParameter);
        }
    }
}
