//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    
    public partial class SPE_OBTIENE_C_VERSION_Result
    {
        public System.Guid ID_VERSION { get; set; }
        public decimal NO_RELEASE { get; set; }
        public string DS_VERSION { get; set; }
        public System.Guid ID_MODULO { get; set; }
        public string NB_MODULO { get; set; }
        public string CL_MODULO { get; set; }
    }
}
