//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    
    public partial class SPE_OBTIENE_S_CONFIGURACION_Result
    {
        public string XML_CONFIGURACION { get; set; }
        public byte[] FI_LOGOTIPO { get; set; }
    }
}
