//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    
    public partial class SPE_OBTIENE_C_CATALOGO_VALOR_Result
    {
        public int ID_CATALOGO_VALOR { get; set; }
        public string CL_CATALOGO_VALOR { get; set; }
        public string NB_CATALOGO_VALOR { get; set; }
        public string DS_CATALOGO_VALOR { get; set; }
        public int ID_CATALOGO_LISTA { get; set; }
        public string NB_CATALOGO_LISTA { get; set; }
    }
}
