//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    
    public partial class SPE_OBTIENE_INFORMACION_CLIENTE_Result
    {
        public Nullable<System.Guid> ID_CLIENTE { get; set; }
        public string CL_CLIENTE { get; set; }
        public string FE_CREACION { get; set; }
        public string CL_PASSWORD { get; set; }
        public string CATALOGOS { get; set; }
    }
}
