//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    
    public partial class SPE_OBTIENE_C_USUARIO_Result
    {
        public string CL_USUARIO { get; set; }
        public string NB_USUARIO { get; set; }
        public string NB_CORREO_ELECTRONICO { get; set; }
        public string NB_PASSWORD { get; set; }
        public bool FG_CAMBIAR_PASSWORD { get; set; }
        public string XML_PERSONALIZACION { get; set; }
        public int ID_ROL { get; set; }
        public Nullable<int> ID_EMPLEADO { get; set; }
        public bool FG_ACTIVO { get; set; }
        public Nullable<System.DateTime> FE_INACTIVO { get; set; }
        public string DS_FILTRO { get; set; }
    }
}
