//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    
    public partial class SPE_OBTIENE_ROL_Result
    {
        public int ID_ROL { get; set; }
        public string CL_ROL { get; set; }
        public string NB_ROL { get; set; }
        public bool FG_ACTIVO { get; set; }
        public string XML_AUTORIZACION { get; set; }
    }
}
